import "./globals.css";
import { Elsie, Inter } from "next/font/google";

const elsie = Elsie({
  display: "swap",
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={elsie.className}>{children}</body>
    </html>
  );
}
